# Generated by Django 3.2.8 on 2021-10-17 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, unique=True)),
                ('Description', models.CharField(max_length=20)),
                ('Genre', models.CharField(max_length=20)),
                ('Language', models.CharField(max_length=20)),
                ('CountryOfOrigin', models.CharField(max_length=20)),
                ('Duration', models.IntegerField(default=90)),
                ('rating', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='11:00')),
                ('total_seats', models.IntegerField(default=20)),
                ('available_seats', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.show')),
            ],
            options={
                'unique_together': {('category', 'show')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mode_of_payment', models.CharField(default='CASH', max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.booking')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCinemaShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.movie')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.show')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.city'),
        ),
        migrations.AddField(
            model_name='booking',
            name='moviedetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.moviecinemashow'),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.ticket'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
